#!/usr/bin/env node
// scripts/docgen.mjs — derives docs/architecture/generated/ from live source.
// GENERATED outputs are artifacts: edit knowledge/ or source docblocks, not generated/.
// Deterministic: no timestamps, no random; all lists sorted or source-ordered.
// Zero runtime deps beyond node built-ins.

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(new URL('.', import.meta.url).pathname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const GEN_DIR = 'docs/architecture/generated';
const GEN_PATH = path.join(ROOT, GEN_DIR);
const HEADER = '<!-- GENERATED by scripts/docgen — edit knowledge/ or source docblocks, not this file -->';

// ─── source parsers (line-scan / regex; no AST deps) ─────────────────────────

/** Capture the body of `const NAME = { … }` / `NAME: { … }` up to the matching
 *  closing brace at the same indent level. Returns the inner text or null. */
function captureBraced(src, declRe) {
  const m = src.match(declRe);
  if (!m) return null;
  const start = m.index + m[0].length; // char after the `{`
  let depth = 1, i = start;
  for (; i < src.length && depth > 0; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') depth--;
  }
  return src.slice(start, i - 1);
}

/** Parse flat `KEY: 'value'` pairs (in declaration order) from a braced body. */
function parsePairs(body) {
  const out = [];
  const re = /([A-Za-z_$][\w$]*)\s*:\s*'([^']*)'/g;
  let m;
  while ((m = re.exec(body)) !== null) out.push([m[1], m[2]]);
  return out;
}

function deriveDb() {
  const src = read('js/db.js');
  const storesBody = captureBraced(src, /DB\s*=\s*\{[\s\S]*?STORES\s*:\s*\{/);
  const stores = storesBody ? parsePairs(storesBody) : [];
  const tableBody = captureBraced(src, /const _TABLE_MAP\s*=\s*\{/);
  const tables = {};
  if (tableBody) {
    const re = /([A-Za-z_$][\w$]*)\s*:\s*('([^']*)'|null)/g;
    let m;
    while ((m = re.exec(tableBody)) !== null) {
      tables[m[1]] = m[3] !== undefined ? m[3] : null;
    }
  }
  return { stores, tables };
}

function deriveConstants() {
  const src = read('js/constants.js');
  const entityBody = captureBraced(src, /export const ENTITY_TO_STORE\s*=\s*\{/);
  const entityToStore = entityBody ? parsePairs(entityBody) : [];
  const enums = {};
  for (const name of ['STORY_STATUS', 'EPIC_STATUS', 'FOCUS_STATUS', 'SPRINT_STATUS', 'REVIEW_STATE', 'ATTACHMENT_TYPES']) {
    const body = captureBraced(src, new RegExp(`export const ${name}\\s*=\\s*\\{`));
    enums[name] = body ? parsePairs(body) : [];
  }
  return { entityToStore, enums };
}

function deriveBuildFiles() {
  const src = read('build.js');
  const m = src.match(/const\s+JS_FILES\s*=\s*\[([\s\S]*?)\]/);
  if (!m) return [];
  const files = [];
  const re = /'([^']+)'/g;
  let mm;
  while ((mm = re.exec(m[1])) !== null) files.push(mm[1]);
  return files;
}

function deriveMigrations() {
  const src = read('js/migrationRunner.js');
  const listBody = src.match(/const MIGRATIONS\s*=\s*\[([\s\S]*?)\]/);
  const names = listBody
    ? (listBody[1].match(/([A-Za-z_$][\w$]*)\b/g) || []).filter((n) => /^migrate/.test(n))
    : [];
  // guard keys: DB.get(DB.STORES.METADATA, '<key>') in source order
  const guards = [];
  const re = /DB\.get\(DB\.STORES\.METADATA,\s*'([^']+)'[^)]*\)/g;
  let m;
  while ((m = re.exec(src)) !== null) guards.push(m[1]);
  return names.map((name, i) => ({ name, guard: guards[i] || '?' }));
}

function deriveNotifications() {
  const files = deriveBuildFiles().filter((f) => f.endsWith('.js'));
  const emit = {};   // type -> Set(files)
  const listen = {}; // type -> Set(files)
  for (const f of files) {
    let src;
    try { src = read(f); } catch { continue; }
    if (!src) continue;
    const fileLabel = f.replace(/^js\//, '');
    let m;
    // strip comments so doc/example calls (e.g. notificationRegistry.js header)
    // are not counted as real emit/listen sites.
    const code = src
      .replace(/\/\*[\s\S]*?\*\//g, ' ')
      .replace(/\/\/[^\n]*/g, '');
    const eRe = /NotificationRegistry\.emit\(\s*['"]([^'"]+)['"]/g;
    while ((m = eRe.exec(code)) !== null) {
      (emit[m[1]] ||= new Set()).add(fileLabel);
    }
    const onRe = /NotificationRegistry\.on\(\s*['"]([^'"]+)['"]/g;
    while ((m = onRe.exec(code)) !== null) {
      (listen[m[1]] ||= new Set()).add(fileLabel);
    }
  }
  const toArr = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, [...v].sort()]));
  return { emit: toArr(emit), listen: toArr(listen) };
}

// Entity-record id construction. Ids are bound to differently-named variables
// (`id`, `planId`, `TAB_ID`, `snapshotId`, …) or returned from helpers, so we key
// on the id-shaped template literal itself: a backtick literal of the form
// `` `<word>-${ `` or the generic `` `${param}-${Date.now()} `` form, plus
// bare `crypto.randomUUID()`. Deduped by stem.
function deriveIdPatterns() {
  const files = deriveBuildFiles().filter((f) => f.endsWith('.js'));
  const byStem = {}; // stem -> [sites]
  const add = (stem, site) => (byStem[stem] ||= []).push(site);
  for (const f of files) {
    let src;
    try { src = read(f); } catch { continue; }
    if (!src) continue;
    const fileLabel = f.replace(/^js\//, '');
    const lines = src.split('\n');
    lines.forEach((line, i) => {
      let m;
      const re1 = /`([a-z][a-z0-9-]*-)\$\{/g;
      while ((m = re1.exec(line)) !== null) add(m[1], `${fileLabel}:${i + 1}`);
      const re2 = /`\$\{(\w+)\}-\$\{Date\.now\(\)/g;
      while ((m = re2.exec(line)) !== null) add(`\${${m[1]}}-`, `${fileLabel}:${i + 1}`);
      if (/crypto\.randomUUID\(\)/.test(line)) add('crypto.randomUUID()', `${fileLabel}:${i + 1}`);
    });
  }
  return Object.entries(byStem)
    .map(([stem, sites]) => ({ stem, sites: [...new Set(sites)].sort() }))
    .sort((a, b) => a.stem.localeCompare(b.stem));
}

// ─── exported globals + docblocks ────────────────────────────────────────────

function deriveExports() {
  const files = deriveBuildFiles().filter((f) => f.endsWith('.js'));
  // global -> [files]; derived from every `window.<NAME> =` assignment.
  const byGlobal = {};
  const byFile = {}; // file -> Set(global)
  for (const f of files) {
    let src;
    try { src = read(f); } catch { continue; }
    if (!src) continue;
    const fileLabel = f.replace(/^js\//, '');
    const re = /window\.([A-Za-z_$][\w$]*)\s*=(?![=])/g;
    let m;
    while ((m = re.exec(src)) !== null) {
      const name = m[1];
      (byGlobal[name] ||= new Set()).add(fileLabel);
      (byFile[fileLabel] ||= new Set()).add(name);
    }
  }
  return {
    globals: Object.keys(byGlobal).sort(),
    byFile: Object.fromEntries(Object.entries(byFile).map(([k, v]) => [k, [...v].sort()])),
  };
}

/** Collect the contiguous comment block immediately above line `idx` (0-based). */
function commentBlockAbove(lines, idx) {
  let j = idx - 1;
  const block = [];
  while (j >= 0) {
    const t = lines[j].trim();
    if (t === '' ) break;
    if (t.startsWith('//')) { block.unshift(lines[j]); j--; continue; }
    if (t.startsWith('/*') || t.startsWith('*') || t.endsWith('*/')) { block.unshift(lines[j]); j--; continue; }
    break;
  }
  return block.join('\n');
}

/** Scan a file's docblocks; return array of { tags: {owns:[], intent:[], rationale:[], see:[]}, file, line }.
 *  A docblock is any maximal run of consecutive comment lines; only runs containing
 *  at least one @owns/@intent/@rationale/@see tag are recorded. Decoupled from
 *  symbol-line detection so method/branch docblocks render too. */
function extractTags(block) {
  const tags = { owns: [], intent: [], rationale: [], see: [] };
  for (const raw of block.split('\n')) {
    const grab = (re, n) => { let m; while ((m = re.exec(raw)) !== null) tags[n].push(m[1].trim()); };
    grab(/@owns\s+([^\n]+)/g, 'owns');
    grab(/@intent\s+([^\n]+)/g, 'intent');
    grab(/@rationale\s+([^\n]+)/g, 'rationale');
    grab(/@see\s+(ADR-\d+)/g, 'see');
  }
  return tags;
}

function deriveDocblocks() {
  const files = deriveBuildFiles().filter((f) => f.endsWith('.js'));
  const blocks = [];
  const isCmt = (t) => t.startsWith('//') || t.startsWith('/*') || t.startsWith('*') || t.endsWith('*/');
  for (const f of files) {
    let src;
    try { src = read(f); } catch { continue; }
    if (!src) continue;
    const fileLabel = f.replace(/^js\//, '');
    const lines = src.split('\n');
    let i = 0;
    while (i < lines.length) {
      if (!isCmt(lines[i].trim())) { i++; continue; }
      let j = i;
      while (j < lines.length) {
        const t = lines[j].trim();
        if (t === '' ) break;
        if (isCmt(t)) { j++; continue; }
        break;
      }
      const block = lines.slice(i, j).join('\n');
      if (/@owns|@intent|@rationale|@see/.test(block)) {
        const tags = extractTags(block);
        if (tags.owns.length || tags.intent.length || tags.rationale.length || tags.see.length) {
          blocks.push({ file: fileLabel, line: i + 1, tags });
        }
      }
      i = j;
    }
  }
  return blocks;
}

// ─── authored channels (flat dotted-key YAML; built-in parse) ────────────────

function parseFlatYaml(relPath) {
  let src;
  try { src = read(relPath); } catch { return {}; }
  const out = {};
  for (const raw of src.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

// schema.yaml -> { store: { field_or_meta: { note, fk, ... } } }
function loadSchema() {
  const flat = parseFlatYaml('docs/architecture/knowledge/annotations/schema.yaml');
  const stores = {};
  for (const [k, v] of Object.entries(flat)) {
    const [store, ...rest] = k.split('.');
    const field = rest.join('.') || '_value';
    (stores[store] ||= {})[field] = v;
  }
  return stores;
}

// ─── render helpers ──────────────────────────────────────────────────────────

const esc = (s) => String(s).replace(/\|/g, '\\|');

function renderRegistry(ctx) {
  const { stores, tables, entityToStore, enums, migrations, buildFiles, idPatterns } = ctx;
  const entityForStore = Object.fromEntries(entityToStore.map(([e, s]) => [s, e]));
  const L = [];
  L.push(HEADER, '', '# REGISTRY — Structural Facts', '');
  L.push('> Pure structure derived from source. Counts are read from live code.', '');
  L.push(`- **DB.STORES count:** ${stores.length}`);
  L.push(`- **Supabase tables:** ${Object.values(tables).filter(Boolean).length} (+ 1 localStorage-only \`metadata\`)`);
  L.push(`- **ENTITY_TO_STORE count:** ${entityToStore.length}`);
  L.push(`- **JS_FILES (build order) count:** ${buildFiles.length}`);
  L.push(`- **MIGRATIONS count:** ${migrations.length}`, '');

  L.push('## Stores ↔ entities ↔ tables', '');
  L.push('| STORES key | store | Supabase table | entity |');
  L.push('|---|---|---|---|');
  for (const [key, store] of stores) {
    const tbl = tables[store];
    const ent = entityForStore[store] || '—';
    L.push(`| ${key} | \`${store}\` | ${tbl === null ? '_(localStorage)_ `null`' : `\`${tbl}\``} | ${ent !== '—' ? `\`${ent}\`` : '—'} |`);
  }
  L.push('');

  L.push('## Enums + values', '');
  for (const [name, vals] of Object.entries(enums)) {
    L.push(`**${name}** (${vals.length}): ${vals.map(([, v]) => `\`${v}\``).join(' · ')}`, '');
  }

  L.push('## ID construction patterns (derived sites)', '');
  L.push('> Records are not structurally declared; ids are built ad hoc. This lists');
  L.push('> every distinct id-shaped template stem found in source (HTML attribute');
  L.push('> ids are excluded). Two families coexist (timestamp vs `crypto.randomUUID`).');
  L.push('> See `schema.yaml` for the human lineage notes (e.g. the two subFocus patterns).', '');
  L.push('| stem | sites |');
  L.push('|---|---|');
  for (const s of idPatterns) {
    L.push(`| \`${s.stem}{…}\` | ${s.sites.map((x) => `\`${x}\``).join(', ')} |`);
  }
  L.push('');

  L.push('## Build order (JS_FILES)', '');
  buildFiles.forEach((f, i) => L.push(`${i + 1}. \`${f}\``));
  L.push('');

  L.push('## Migration list (ordered, with guard keys)', '');
  migrations.forEach((m, i) => L.push(`${i + 1}. \`${m.name}\` — guard: \`${m.guard}\``));
  L.push('');
  return L.join('\n');
}

function renderSystemMap(ctx) {
  const { buildFiles, migrations, exports, docblocks, notes, notifications } = ctx;
  const L = [];
  L.push(HEADER, '', '# SYSTEM_MAP — Modules + Coordination', '');
  L.push('> Module table joined from source docblocks. Behavioral notes from `system.yaml`.', '');

  // docblocks grouped by file
  const dbByFile = {};
  for (const d of docblocks) (dbByFile[d.file] ||= []).push(d);

  L.push('## Build order', '');
  buildFiles.forEach((f, i) => L.push(`${i + 1}. \`${f}\``));
  L.push('');

  L.push('## Module table', '');
  L.push('| # | module | exports | @owns |');
  L.push('|---|---|---|---|');
  buildFiles.forEach((f, i) => {
    const label = f.replace(/^js\//, '').replace(/^vendor\//, 'vendor/');
    const exps = (exports.byFile[label] || []);
    const owns = (dbByFile[label] || [])
      .flatMap((d) => d.tags.owns).filter(Boolean);
    L.push(`| ${i + 1} | \`${label}\` | ${exps.map((e) => `\`${e}\``).join(', ') || '—'} | ${owns.map((o) => o.replace(/\s+/g, ' ')).join('; ') || '—'} |`);
  });
  L.push('');

  L.push('## Behavioral notes (source docblocks: @intent / @rationale / @see)', '');
  const intentBlocks = docblocks.filter((d) => d.tags.intent.length || d.tags.rationale.length);
  if (intentBlocks.length) {
    for (const d of intentBlocks) {
      const here = [];
      if (d.tags.intent.length) here.push(...d.tags.intent.map((t) => `**@intent:** ${t}`));
      if (d.tags.rationale.length) here.push(...d.tags.rationale.map((t) => `**@rationale:** ${t}`));
      if (d.tags.see.length) here.push(...d.tags.see.map((t) => `**@see:** ${t}`));
      L.push(`- \`${d.file}:${d.line}\` — ${here.join(' ')}`);
    }
  } else {
    L.push('_(none yet — seed `@intent`/`@rationale` in source docblocks.)_');
  }
  L.push('');

  L.push('## Migration ordering', '');
  migrations.forEach((m, i) => L.push(`${i + 1}. \`${m.name}\` — guard \`${m.guard}\``));
  L.push('');

  L.push('## Notification emit / listen map', '');
  const types = [...new Set([...Object.keys(notifications.emit), ...Object.keys(notifications.listen)])].sort();
  L.push('| type | emitted by | listened by |');
  L.push('|---|---|---|');
  for (const t of types) {
    L.push(`| \`${t}\` | ${(notifications.emit[t] || []).map((f) => `\`${f}\``).join(', ') || '—'} | ${(notifications.listen[t] || []).map((f) => `\`${f}\``).join(', ') || '—'} |`);
  }
  L.push('');

  L.push('## Topic notes (from `system.yaml`)', '');
  const topics = ['notification', 'channel', 'cache'];
  for (const t of topics) {
    const entries = Object.entries(notes).filter(([k]) => k.startsWith(t + '.'));
    if (!entries.length) continue;
    L.push(`### ${t}`, '');
    for (const [k, v] of entries) L.push(`- **${k}** — ${v}`);
    L.push('');
  }
  const leftover = Object.entries(notes).filter(([k]) => !topics.some((t) => k.startsWith(t + '.')));
  if (leftover.length) {
    L.push('### other', '');
    for (const [k, v] of leftover) L.push(`- **${k}** — ${v}`);
    L.push('');
  }
  return L.join('\n');
}

function renderSchemaRef(ctx) {
  const { stores, tables, schema } = ctx;
  const L = [];
  L.push(HEADER, '', '# SCHEMA_REFERENCE — Per-store Fields', '');
  L.push('> Field skeletons are **not** structurally declared in source (deferred).');
  L.push('> This lists every store (coverage-complete) and renders the fields annotated');
  L.push('> in `schema.yaml`. Add a field note in `schema.yaml` to make it appear here.', '');
  L.push(`- **Stores documented:** ${stores.length} (all of \`DB.STORES\`)`, '');

  for (const [key, store] of stores) {
    const tbl = tables[store];
    const annot = schema[store] || {};
    L.push(`## ${key} → \`${store}\``, '');
    L.push(`Supabase table: ${tbl === null ? '_localStorage only (not synced)_' : `\`${tbl}\``}`, '');
    const storeNote = annot._store;
    if (storeNote) L.push(`> ${storeNote}`, '');
    const fields = Object.keys(annot).filter((k) => k !== '_store' && k !== '_value');
    if (fields.length) {
      L.push('| field | note |');
      L.push('|---|---|');
      for (const fld of fields.sort()) L.push(`| \`${fld}\` | ${esc(annot[fld])} |`);
    } else {
      L.push('_(no field annotations yet — add `store.field: note` in `schema.yaml`.)_');
    }
    L.push('');
  }
  return L.join('\n');
}

// ─── main (guarded so doc-checks can import the derivations without side effects) ─

export {
  deriveDb, deriveConstants, deriveBuildFiles, deriveMigrations,
  deriveNotifications, deriveIdPatterns, deriveExports, deriveDocblocks,
  loadSchema, parseFlatYaml, GEN_DIR,
};

function main() {
  const { stores, tables } = deriveDb();
  const { entityToStore, enums } = deriveConstants();
  const buildFiles = deriveBuildFiles();
  const migrations = deriveMigrations();
  const notifications = deriveNotifications();
  const idPatterns = deriveIdPatterns();
  const exports = deriveExports();
  const docblocks = deriveDocblocks();
  const schema = loadSchema();
  const notes = parseFlatYaml('docs/architecture/knowledge/annotations/system.yaml');

  const ctx = { stores, tables, entityToStore, enums, buildFiles, migrations, notifications, idPatterns, exports, docblocks, schema, notes };

  fs.mkdirSync(GEN_PATH, { recursive: true });
  const outDir = process.env.DOCGEN_OUT ? path.join(ROOT, process.env.DOCGEN_OUT) : GEN_PATH;
  fs.mkdirSync(outDir, { recursive: true });
  const out = {
    'REGISTRY.md': renderRegistry(ctx),
    'SYSTEM_MAP.md': renderSystemMap(ctx),
    'SCHEMA_REFERENCE.md': renderSchemaRef(ctx),
  };
  for (const [name, content] of Object.entries(out)) {
    fs.writeFileSync(path.join(outDir, name), content.replace(/\n{3,}/g, '\n\n') + '\n', 'utf8');
    console.log(`  ${process.env.DOCGEN_OUT ? process.env.DOCGEN_OUT + '/' : 'generated/'}${name}`);
  }
  console.log(`\nDocgen complete — ${stores.length} stores, ${buildFiles.length} build files, ${exports.globals.length} exported globals.`);
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) main();
